// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using Microsoft.VisualBasic;

namespace Contensive.Addon.aoFormWizard3.My.Resources {

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    var temp = new System.Resources.ResourceManager("Contensive.Addon.aoFormWizard3.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to 	&lt;div class=&quot;designBlockContainer blockText&quot; style=&quot;{{styleHeight}}{{styleBackgroundImage}}&quot;&gt;
        /// 	&lt;div class=&quot;{{contentContainerClass}}&quot;&gt;
        /// 	&lt;div class=&quot;form-group &quot;&gt;
        ///      &lt;h2&gt;{{headerline}}&lt;/h2&gt;
        /// 	  &lt;div&gt;{{description}}&lt;/div&gt;
        ///     &lt;/div&gt;
        /// 	 {{#listOfFieldsClass}}	
        /// 
        ///     {{#isDefault}}
        ///     &lt;div class=&quot;form-group px-1&quot;&gt;
        /// 	
        /// 	{{#headline}}
        /// 	 &lt;h4&gt;{{headline}}&lt;/h4&gt;
        /// 	 {{/headline}}
        /// 	 {{#fielddescription}}
        /// 	   &lt;p class=&quot;pl-5&quot;&gt;{{fielddescription}}&lt;/p&gt;
        /// 	 {{/fielddescription}}
        ///      &lt;label class=&quot;control-l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormWizard {
            get {
                return ResourceManager.GetString("FormWizard", resourceCulture);
            }
        }
    }
}